service_name: transmission
net_name: warez

net_in: [
  '# {{ service_name }}',
  '-A TCP -i {{ dev_WAN }} -p tcp -m tcp --dport 51413 -m conntrack --ctstate NEW -j ACCEPT',
  '-A UDP -i {{ dev_WAN }} -p udp -m udp --dport 51413 -m conntrack --ctstate NEW -j ACCEPT'
]
net_out: [
  '# {{ service_name }}',
  '-A OUTPUT -o br-{{ eth_hash }} -p tcp -m tcp --dport 9091 -m conntrack --ctstate NEW -j ACCEPT'
]
net_forward: [
  '# {{ service_name }}',
  '# transmission querying internet',
  '-A FORWARD -i br-{{ eth_hash }} -o {{ dev_WAN }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT',
  '-A FORWARD -i br-{{ eth_hash }} -o {{ dev_WAN }} -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW -j ACCEPT',
  '# transmission listen port',
  '-A FORWARD -i {{ dev_WAN }} -o br-{{ eth_hash }} -p tcp -m tcp --dport 51413 -m conntrack --ctstate NEW -j ACCEPT',
  '-A FORWARD -i {{ dev_WAN }} -o br-{{ eth_hash }} -p udp -m udp --dport 51413 -m conntrack --ctstate NEW -j ACCEPT',
  '# transmission sharing/requesting content?',
  '-A FORWARD -i br-{{ eth_hash }} -o {{ dev_WAN }} -p udp -m udp --sport 51413 -m conntrack --ctstate NEW -j ACCEPT',
  '-A FORWARD -i br-{{ eth_hash }} -o {{ dev_WAN }} -p tcp -m tcp --sport 51413 -m conntrack --ctstate NEW -j ACCEPT',
  '# Vagrant needs network traffic',
  '-A FORWARD -i br-{{ eth_hash }} -o br-{{ eth_hash }} -j ACCEPT'
]
net_nat: [
  '# {{ service_name }}',
  '# transmission listen port',
  '-A PREROUTING -i {{ dev_WAN }} -p tcp -m tcp --dport 51413 -j DNAT --to-destination {{ container_ip }}',
  '-A PREROUTING -i {{ dev_WAN }} -p udp -m udp --dport 51413 -j DNAT --to-destination {{ container_ip }}'
]

services:
  - name: "transmission.{{ name_VPN }}.vpn"
    destination: transmission:9091