---
- name: easy-rsa  |  Installing easy-rsa software
  apt: pkg=easy-rsa state=present

- include: bionic-setup.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == 'bionic'

- include: focal-setup.yml
  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'focal') or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'hirsute') or
        (ansible_distribution == 'Debian')

- include: crl.yml

- include: build.yml
  tags: [ never, build_ovpn ]

- include: revoke.yml
  tags: [ never, revoke_ovpn ]
