---

- name: monitoring  |  Create destiny
  file:
    path: /opt/monitoring
    state: directory
    mode: '0750'

- name: monitoring  |  Alertmanager config
  template: 
    src: alertmanager/config.yml
    dest: /opt/monitoring/alertmanager/
    owner: root
    group: root
    mode: 0644

- name: monitoring  |  Create grafana dir
  file:
    path: /opt/monitoring/grafana/{{ item }}
    state: directory
    mode: '0750'
  with_items:
  - dashboards
  - provisioning/dashboards
  - provisioning/datasources

- name: monitoring  |  Grafana dashboards
  copy: 
    src: grafana/dashboards/{{ item }}
    dest: /opt/monitoring/grafana/dashboards
    owner: root
    group: root
    mode: 0640
  with_items:
    - docker.json
    - node-exporter-full_rev15.json
    - speedtest-dashboard_rev1.json

- name: monitoring  |  Grafana provisioning dashboards
  copy: 
    src: grafana/provisioning/dashboards/ansible.yaml
    dest: /opt/monitoring/grafana/provisioning/dashboards
    owner: root
    group: root
    mode: 0640

- name: monitoring  |  Grafana provisioning datasources
  copy: 
    src: grafana/provisioning/datasources/prometheus.yaml
    dest: /opt/monitoring/grafana/provisioning/datasources/
    owner: root
    group: root
    mode: 0640

- name: monitoring  |  Create prometheus dir
  file:
    path: /opt/monitoring/prometheus
    state: directory
    mode: '0705'

- name: monitoring  |  Prometheus config
  template: 
    src: prometheus.yml
    dest: /opt/monitoring/prometheus
    owner: root
    group: root
    mode: 0604

- name: monitoring  |  Prometheus alerts
  copy: 
    src: alert.rules
    dest: /opt/monitoring/prometheus
    owner: root
    group: root
    mode: 0604

- name: monitoring  |  Copy docker-compose
  template: 
    src: docker-compose.yml
    dest: /opt/monitoring
    owner: root
    group: root
    mode: 0600
  register: newdocker

- name: monitoring  |  Tear down existing services
  docker_compose:
    project_src: /opt/monitoring
    #remove_images: yes
    remove_volumes: yes
    state: absent
  tags: uninstall, never
    
- name: monitoring  |  Create and start services
  docker_compose:
    project_src: /opt/monitoring
  when: newdocker.changed

- name: monitoring  |  Copy proxy config
  include_role:
    name: proxy-http
  vars:
    network_name: "{{ net_name }}"
    virtualhosts: "{{ services }}"

- name: monitoring  |  Get docker network name 1/2
  community.general.docker_network_info:
    name: "{{ service_name }}_{{ net_name }}"
  register: docker_net

- name: monitoring  |  Get docker network name 2/2
  set_fact:
    eth_hash: "{{ docker_net.network.Id[:12] }}"

- name: monitoring  |  Apply iptables rules
  include_role:
    name: firewall

- name: monitoring  |  Add DNS to Pi-hole
  lineinfile:
    path: /opt/pihole/etc-pihole/custom.list
    state: present
    regexp: '^{{ ip_VPN }} {{ item }}.{{ name_VPN }}.vpn'
    line: '{{ ip_VPN }} {{ item }}.{{ name_VPN }}.vpn'
  loop:
    - alertmanager
    - cadvisor
    - grafana
    - prometheus
