---

- name: OS  |  Installing software
  apt: pkg=openvpn state=present

- name: Configure openvpn with generated certificates
  block:
  
  - include: bionic-setup.yml
    when: ansible_distribution == "Ubuntu" and ansible_distribution_release == 'bionic'
  
  - include: focal-setup.yml
    when: (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'focal') or
          (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'hirsute') or
          (ansible_distribution == 'Debian')
  
  - name: vpn  |  Create clients config dir
    file:
      path: /etc/openvpn/server/client-config
      state: directory
      mode: '0500'
  
  - name: vpn  |  Configuring openvpn server
    template: src=vpn-server.conf.j2 dest=/etc/openvpn/{{ name_VPN }}.conf owner=root group=root mode=0400
    #notify:
    #- restart "openvpn@{{ name_VPN }}"
  
  when: not restore_backup

- name: Restore openvpn configuration from backup
  unarchive:
    src: backup/vpn-server/vpn-server.tar.gz
    dest: /
  when: restore_backup


- name: vpn  |  Ensure OpenVPN is started
  service:
    name: "openvpn@{{ name_VPN }}"
    state: restarted
    enabled: true
    daemon_reload: yes

- name: iptables  |  Enabling ip forwarding
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward=1'
    line: net.ipv4.ip_forward=1


- name: iptables  |  Apply iptables rules
  include_role:
    name: firewall
