---
- name: disable haproxy
  service:
    name: haproxy
    state: stopped
    enabled: no
    daemon_reload: yes

- name: restart-keepalived
  service:
    name: keepalived
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart iptables
  service:
    name: netfilter-persistent
    state: restarted
