---
- name: emby  |  Create destiny
  file:
    path: /opt/emby
    state: directory
    mode: '0750'
  tags: install

- name: emby  |  Copy docker-compose
  template: 
    src: docker-compose.yml
    dest: /opt/emby/
    owner: root
    group: root
    mode: 0600 
  tags: install
  register: newdocker

- name: emby  |  Tear down existing services
  docker_compose:
    project_src: /opt/emby
    #remove_images: yes
    remove_volumes: yes
    state: absent
  tags: uninstall, never
    
- name: emby  |  Create and start services
  docker_compose:
    project_src: /opt/emby
  when: newdocker.changed
  tags: install

- name: emby  |  Copy proxy config
  include_role:
    name: proxy-http
  vars:
    network_name: "{{ net_name }}"
    virtualhosts: "{{ services }}"
  tags: install

- name: emby  |  Get docker network name 1/2
  community.general.docker_network_info:
    name: "{{ service_name }}_{{ net_name }}"
  register: docker_net
  tags: install

- name: emby  |  Get docker network name 2/2
  set_fact:
    eth_hash: "{{ docker_net.network.Id[:12] }}"
  tags: install

- name: emby  |  Apply iptables rules
  include_role:
    name: firewall
  tags: install

- name: emby  |  Add DNS to Pi-hole
  lineinfile:
    path: /opt/pihole/etc-pihole/custom.list
    state: present
    regexp: '^{{ ip_VPN }} {{ item }}.{{ name_VPN }}.vpn'
    line: '{{ ip_VPN }} {{ item }}.{{ name_VPN }}.vpn'
  loop:
    - emby
  tags: install
