---
- name: Create backup path
  file:
    path: "{{ remote_backup_path }}"
    state: directory
  
- name: "Upload backup file {{ docker_volume }}"
  copy:
    src: "{{ local_backup_path }}/{{ docker_volume }}-{{ docker_date }}.tar"
    dest: "{{ remote_backup_path }}"

- name: Create volume
  docker_volume:
    name: "{{ docker_volume }}"
  
- name: Restore volume
  docker_container:
    name: backup_qdpaas
    image: alpine
    volumes:
      - "{{ docker_volume }}:/volume"
      - "{{ remote_backup_path }}:/backup"
    entrypoint: "{{ restore_command }}"

# too fast to catch
#- name: Wait for the restore to start
#  docker_container_info:
#    name: backup_qdpaas
#  register: result
#  until: result.container.State.Status == 'running'

- name: Wait 30 minutes for the restore to complete
  docker_container_info:
    name: backup_qdpaas
  register: result
  retries: 600
  until: result.container.State.Status == 'exited'
  