{
 "title": "Speedtest Dashboard",
 "description": "A dashboard for Prometheus Speedtest Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current Download Speed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    { "expr": "download_speed_bps", "legendFormat": "Download Speed" }
   ]
  },
  {
   "title": "Ping Latency Timeline",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Ping Latency (ms)" }
   ],
   "targets": [
    { "expr": "ping_ms", "legendFormat": "Ping" }
   ]
  },
  {
   "title": "Current Upload Speed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    { "expr": "upload_speed_bps", "legendFormat": "Upload Speed" }
   ]
  },
  {
   "title": "Current Ping Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ping_ms", "legendFormat": "Ping Latency" }
   ]
  },
  {
   "title": "Speedtest Timeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbits", "label": "Speed Mbps" }
   ],
   "targets": [
    { "expr": "download_speed_bps", "legendFormat": "Download Speed" },
    { "expr": "upload_speed_bps", "legendFormat": "Upload Speed" }
   ]
  }
 ]
}