---
- name: docker  |  Removing previous versions
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
      - docker-ce
      - docker-ce-cli
      - docker-compose
    state: absent
  tags: [ never, uninstall ]



- include: bionic-setup.yml
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_release == 'bionic') or
        (ansible_distribution == 'Debian')

- include: focal-setup.yml
  when: (ansible_distribution == 'Ubuntu') and 
        (ansible_distribution_release == 'focal' or ansible_distribution_release == 'hirsute')



- name: docker  |  Create folder for persistent data
  file:
    path: /docker-share
    state: directory
    owner: www-data
    group: www-data
    mode: 0750

- name: docker  |  Disable autogeneration of iptables rules
  copy:
    src: daemon.json
    dest: /etc/docker/

- name: docker  |  Restart service in order to disable iptables autogeneration
  systemd:
    state: restarted
    name: docker
    enabled: yes
