service_name: pihole
net_name: default

pihole_pass: '1234'

net_in: [
  '# {{ service_name }}',
  '# vpn clients querying pihole',
  '-A UDP -i {{ dev_VPN }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT',
  '# pihole admin console',
  '-A TCP -i {{ dev_VPN }} -p tcp -m tcp --dport 8080 -m conntrack --ctstate NEW -j ACCEPT'
]
net_out: [
  '# {{ service_name }}',
  '# pihole querying internet',
  '-A OUTPUT -o br-{{ eth_hash }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT',
  '-A OUTPUT -o br-{{ eth_hash }} -p tcp -m multiport --dports 80,443 -m conntrack --ctstate NEW -j ACCEPT'
]
net_forward: [
  '# {{ service_name }}',
  '-A FORWARD -i br-{{ eth_hash }} -o {{ dev_WAN }} -j ACCEPT',
  '-A FORWARD -i {{ dev_WAN }} -o br-{{ eth_hash }} -j ACCEPT'
]
net_nat: []
